#!/bin/bash

# clean.sh: Removes all build artifacts generated by browser.pro

# Exit on any error
set -e

echo "Cleaning build artifacts..."

# Remove QuickDOM.app
if [ -d "QuickDOM.app" ]; then
    rm -rf QuickDOM.app
    echo "Removed QuickDOM.app"
else
    echo "QuickDOM.app not found, skipping"
fi

# Remove Makefiles and qmake cache
for file in Makefile Makefile.Debug Makefile.Release .qmake.stash .qmake.cache; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Removed $file"
    else
        echo "$file not found, skipping"
    fi
done

# Remove build directory (if specified in browser.pro, adjust if different)
if [ -d "build" ]; then
    rm -rf build
    echo "Removed build directory"
else
    echo "build directory not found, skipping"
fi

# Remove media cache directory
if [ -d "cache" ]; then
    rm -rf cache
    echo "Removed cache directory"
else
    echo "cache directory not found, skipping"
fi

# Remove temporary tab files (e.g., tab_0.html)
for file in tab_*.html; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Removed $file"
    fi
done

for file in moc_*; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Removed $file"
    fi
done

for file in *.o; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Removed $file"
    fi
done

echo "Cleanup complete!"